root = "."

tmp_dir = "tmp"

[build]
  cmd = "go build -gcflags='all=-N -l' -o ./tmp/main.exe ."
  bin = ".\\tmp\\main.exe"
  full_bin = ".\\tmp\\main.exe"
  exclude_dir = ["tmp"]
  include_ext = ["go"]

[log]
  main_only = true

[misc]
  clean_on_exit = true
