root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "./tmp/main"
delay = 1000
exclude_dir = ["tmp"]
include_ext = ["go"]
env_file = [".env"]

[log]
time = true

[misc]
clean_on_exit = true
