root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main"
  cmd = "go build -o ./tmp/main ."
  include_ext = ["go", "html"]
  exclude_dir = ["tmp", ".git"]
  delay = 1000

[proxy]
  enabled = true
  proxy_port = 3001
  app_port = 3000
